"""Write site-packages path hook so buddy needs no PYTHONPATH after install."""
from __future__ import annotations

import os
import site
import sys
from pathlib import Path


def _workspace() -> Path:
    from .paths import workspace_root

    return workspace_root()


def write_pth() -> dict:
    """Create supagen_workspace.pth in user site-packages."""
    root = _workspace()
    prime_scripts = root / "prime" / "scripts"
    harness = root / "harness"
    lines = [
        f"# auto-generated by supagen bootstrap — root={root}",
        str(prime_scripts.resolve()),
        str(harness.resolve()),
        str((harness / "certify" / "v1").resolve()),
        str((harness / "pipeline" / "v1").resolve()),
    ]
    # prefer user site
    user_site = Path(site.getusersitepackages())
    user_site.mkdir(parents=True, exist_ok=True)
    pth = user_site / "supagen_workspace.pth"
    pth.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # also try system site if writable
    written = [str(pth)]
    try:
        for sp in site.getsitepackages():
            spth = Path(sp) / "supagen_workspace.pth"
            try:
                spth.write_text("\n".join(lines) + "\n", encoding="utf-8")
                written.append(str(spth))
            except OSError:
                pass
    except Exception:
        pass

    # env hint file
    env_file = root / "supagen" / "state" / "SUPAGEN_ROOT.txt"
    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text(str(root.resolve()) + "\n", encoding="utf-8")

    return {
        "ok": True,
        "workspace": str(root.resolve()),
        "pth_files": written,
        "prime_scripts_exists": prime_scripts.is_dir(),
        "harness_exists": harness.is_dir(),
        "note": "New Python processes will import dual_enter/jina_service without PYTHONPATH",
    }


def main() -> int:
    import json

    # ensure paths work before write
    from .paths import ensure_sys_path

    ensure_sys_path()
    r = write_pth()
    print(json.dumps(r, indent=2))
    # smoke import in-process after path ensure
    try:
        import nomic_metric  # noqa: F401

        r["import_nomic_metric"] = True
    except Exception as e:
        r["import_nomic_metric"] = False
        r["import_error"] = str(e)
        print(json.dumps(r, indent=2))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
